sudo: required
services:
  - docker

before_install:
  - docker build -t dspham/docker-kubernetes -f Dockerfile.dev .

script:
  - docker run dspham/docker-kubernetes npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-kubernetes"
  env: "DockerKubernetes-env"
  bucket_name: "elasticbeanstalk-us-west-2-089838996481"
  bucket_path: "docker-kubernetes"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

# DockerKubernetes-env.pbez4fgx43.us-west-2.elasticbeanstalk.com



